### PR TITLE
[WIP] Fix Travis

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by MrIbby** [comment]
Can the HTML and iOS modules be removed?

**Comment by ghost** [comment]
@jmrapp1 Can the HTML and iOS modules be removed?

**Comment by jmrapp1** [comment]
I was gonna make those changes myself, but when I was editing it I was out and didn't have the code with me! Thanks for making them!

**Comment by ghost** [comment]
No problem!

**Comment by ghost** [comment]
In `PhysicsGame.gwt.xml`, `com/jmr/physics` should be `com/jmrapp/terralegion`.

**Pull request merged**
