### PR TITLE
added different tree generation

### PR DESCRIPTION
**Pull request by AppPhil**
I'm not sure if this is a good way to implement different trees. What do you think?

### CODE REVIEW

**Comment by jmrapp1** [comment]
You've got the right idea, but the `TreeBlock` isn't a good idea. You should just be using the normal `Block` implementation. For the `TreeGenerator` instead of it returning an `ArrayList<TreeBlock>`, have a `Chunk` instance as a parameter, and have it add the blocks directly to it. There's no need to return them. That way you won't need to use an array. Also since you'll be removing the `TreeBlock` class, when you create new `TreeBlock`'s and you add them to the array, replace that by just using the `BlockManager.getBlock` method and set it directly in the `Chunk`.

**Comment by AppPhil** [comment]
Btw what do you think about using gitter for chatting about TerraLegion?

**Comment by AppPhil** [comment]
I changed what you said: https://github.com/jmrapp1/TerraLegion/pull/30/commits/42a6a60ab34a775d4fd287d873d401e78adda622

**Comment by jmrapp1** [comment]
Great!

**Pull request merged**
