### PR TITLE
Saving inventory should work

### PR DESCRIPTION
**Pull request by AppPhil**
I hope you like this way of saving. If not please don't take this pull request and let me know what you think about it.

### CODE REVIEW

**Comment by jmrapp1** [comment]
Okay so you've got the right idea but there are a few things that need to be taken into account to make this as dynamic as possible. 

The Inventory class is designed to be used with anything that holds items. So the Player, a chest, another entity, etc. It is to be used in many things other than just the Player. Because of this, we need to be saving some type of identifier that tells us what/where the inventory should be loaded into. Right now, only the Player keeps an inventory, but we know that other entities will keep an inventory and we need to take it into account.

Also, the save and load methods should be separated from the Inventory class. The methods should be moved to the WorldIO class, renamed to saveInventory and loadInventory (for example), and both should take an Inventory instance as a parameter. These methods should then be used within the saveWorld and loadWorld methods.

**Comment by AppPhil** [comment]
Why do you mean that the loadInventory method should take an Inventory instance as a parameter? I mean you don't got an instance of it before loading right?

**Comment by jmrapp1** [comment]
Woops, I meant to say the saveInventory method should take an Inventory instance as a parameter and the loadInventory method should return an Inventory instance.

**Comment by AppPhil** [comment]
And what do you think about this:
Should the different inventorys (from player, chests...) be saved in the same file?

**Comment by jmrapp1** [comment]
I would need to put a good amount of thought into it, but I can give you an idea that I have in my head. It would be best, to cut down on the amount of processing, to save the chest inventories in files relative to the chunk that they're in. Chunk files are named "ChunkX_Y.save" where X and Y are the X and Y locations of the chunk in the world. What we can do is create another file for each chunk called "ChunkX_Y_Inventories.save" which contains all inventories on that chunk. 

When it comes to actually saving the information, I imagine it would be best to use a XML library to read and write the actual data. Let me explain why. There can be different types of writing implementations that depend on what is holding the inventory. For example, there will be a writing type for Entities, a writing type for Inventory blocks (chests), etc. For each writing type they will save different information. The entity type might save the entity ID and the entity location. The Inventory block type might save only the block location. The XML would look something similar to this:

> <inventories>
>        <save>
>              <type>InventoryBlock</type>
>               <x>100</x>
>               <y>225</y\>
>               <data>Here is where the saved inventory string would go that would be read and converted to an actual inventory when loaded</data>
>       </save>
>       <save>
>               <type>Entity</type>
>               <id>2</id>
>               <x>300</x>
>               <y>200</y>
>               <data>Here is where the saved inventory string would go that would be read and converted to an actual inventory when loaded</data>
>       </save>
> </inventories>

**Comment by AppPhil** [comment]
Would you save the player inventory in one of the chunk files (from that chunk where players position is in) or in another file? 
Do you know which XML library you would choose?

**Comment by jmrapp1** [comment]
Right now only the player's X and Y position is being saved in the world.save file. I think that what needs to be done is that it needs to be saved in a "player.save" file. It will hold the X and Y position and the inventory data (for now). As more content is added, like stats, that will also be added to the file.

As far as the XML library, thinking about it more now, it'll probably be easier to just use JSON. Check out [this tutorial](http://www.mkyong.com/java/json-simple-example-read-and-write-json/) with JSON.simple. Include it as gradle dependency using `compile group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'`

**Comment by AppPhil** [comment]
I will try that! Thanks!

**Comment by AppPhil** [comment]
What do you think about the player.save looking like this:
{
    "playerPosition":[1226.3534,27936.0],
    "playerInventory":[itemStack,itemStack,itemStack.....]
}

I am not sure if the itemStack should look like: x, y, id, stack

**Comment by jmrapp1** [comment]
Always take into account the possibility that more data will be added in the future. So right now it may just be id, x, y, and stack but it always could have more information when new item types are added. So you need to make it so that adding new data is possible and wouldn't break the system. As long as that holds true, it should work fine.

**Comment by AppPhil** [comment]
I think with an "layout" like this adding more data should be no problem;

{
    "playerInventory":[
        {"stack":1,"x":0,"y":0,"id":7},
        {"stack":25,"x":1,"y":0,"id":5},
        {"stack":1,"x":2,"y":0,"id":12},
        {"stack":5,"x":3,"y":0,"id":2},
        {"stack":5,"x":4,"y":0,"id":3}],
    "playerPosition":[1344.1166,27872.0]
}

What do you think?

**Comment by AppPhil** [comment]
What do you think about a "layout" like this: 

{
    "playerInventory":[
        {
            "stack":1,
            "x":0,
            "y":0,
            "id":7
        },
        {
            "stack":25,
            "x":1,
            "y":0,
            "id":5
        },
        {
            "stack":1,
            "x":2,
            "y":0,
            "id":12
        },
        {
            "stack":5,
            "x":3,
            "y":0,
            "id":2
        },
        {
            "stack":5,
            "x":4,
            "y":0,
            "id":3
        }
     ],
    "playerPosition":[
        {
            "x":1344.1166,
            "y":27872.0
        }
     ]
}

I think here you could easy add more data.

If this would be okay for you here's my implementation of it:
https://github.com/AppPhil/TerraLegion/commit/b4a7036e5b1581289e537d93ae8413f07f09253c

**Comment by jmrapp1** [comment]
I like the implementation a lot! The only change I would like to see is for the logic of the saving and loading inventory moved outside into its own methods. That way it can be used for all inventories.

**Comment by baseball435** [comment]
I like the implementation a lot! The only change I would like to see is for the logic of the saving and loading inventory moved outside into its own methods. That way it can be used for all inventories.

**Comment by AppPhil** [comment]
What do you think about a method which "converts" an inventory to a JSONString? Because then you can use this method for the player inventory and chest inventories. I hope you understand what I mean.

**Comment by jmrapp1** [comment]
I understand exactly what you mean. Thinking about it, this may be something that needs to be done for all kinds of classes. We could use the toString method and override that method for all types that need to be saved. I think this may be the best option. Another option would be to have a utility class of static methods that takes an object, like inventory, and converts it to a string.

**Comment by AppPhil** [comment]
So in this example you would add the toString() method to the Inventory class and that would return the JSONString? But you also need something to load the inventory / create an Inventory instance from a JSONString.

**Comment by jmrapp1** [comment]
Oh you're referring to the class, JSONString, I interpreted it as a JSON formatted string. In that case, the toString() method won't work in this situation. So that leaves us with some type of external class or utility that provides the methods needed to save and load information. Creating a utility class that has static methods that save and load different types would work in this situation I believe

**Comment by AppPhil** [comment]
Yes, sorry for my explaination. With JSONString I just meant a normal String in the JSON format.

**Comment by AppPhil** [comment]
This is what I got now: https://github.com/AppPhil/TerraLegion/commit/f9ecddaa39d2c2a73a00d36d57ac1be7c2467861

I don't know how I can update the code of this pull reuqest.

**Comment by jmrapp1** [comment]
Looks great! You'd have to either create a new branch to create a separate merge or remove the code that doesn't have to do with the pull, place it somewhere else for the time being, pull down the current version of those files that were just moved, and then commit.

**Comment by AppPhil** [comment]
Can you help me with that? I don't understand what to do.

**Comment by jmrapp1** [comment]
Oh wait, I misread your question. I thought there were other files you didn't want to be included in the pull. You should just push the new code and it will update the pull request.

**Comment by AppPhil** [comment]
Wait there are other files that shouldn't be included in the pull.

**Comment by jmrapp1** [comment]
Right, those should be updated when you submit the pull request because it will find that those changed.

**Comment by AppPhil** [comment]
I think I know the problem. I deleted the fork where I opened this pull here and created a new one. That might be the problem. I'm such an idiot. Would it be okay for you if you close this one and I create a new pull?

**Comment by jmrapp1** [comment]
Oh yes, it says that the merge is from an unknown branch. You'll need to submit a new pull.

**Comment by AppPhil** [comment]
Okay I will do. Sorry for this mistake.

**Comment by jmrapp1** [comment]
Not a problem.

**Pull request closed without merging**
