### PR TITLE
Animated Player

### PR DESCRIPTION
**Pull request by shathor**
Player is animated now when he's moving left or right. The spritesheet is just an example, it looks a little blurry because I scaled it up.

### CODE REVIEW

**Comment by jmrapp1** [comment]
That's great! Thank you for your animation implementation! I'll merge, but I'm going to modify where you change the animation. Instead of creating a new `addVelocity` method, I'm going to add it into the current `addVelocity(float x, float y)` and only do the animation if `x != 0 && y == 0`. That way we only have to use one method.

**Comment by shathor** [comment]
Ok thats fine. On another note, I found it suboptimal that the touch gesture is moving the player outside the Player class. It would be better having it in the same method as where you control the player with W, A, D and Space (atleast all player controls at one place)

**Comment by jmrapp1** [comment]
Agreed, these two functionalities should be kept within the same housing, but there's a required separation of them because the `GameHud` needs to hold and manage all touches on the screen while the keyboard input doesn't generally relate to that functionality.

**Comment by shathor** [comment]
In that case I'd move the keyboard stuff to the InputController or Listener or whatever aswell.

**Pull request merged**
